In [560]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [712]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)            # number of layers in the network

    for l in range(1, L):
        
        parameters['W' + str(l)] = (np.random.randn(layer_dims[l], layer_dims[l - 1])) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

        
    return parameters

In [713]:
parameters = initialize_parameters([56,100,1])

print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))


W1 = [[ 0.01788628  0.0043651   0.00096497 ...  0.01119391  0.01487543
  -0.01118301]
 [ 0.00845833 -0.0186089  -0.00602885 ...  0.0031306  -0.00516648
  -0.00189072]
 [-0.00416198  0.00724658 -0.00689961 ... -0.00071219 -0.01486658
   0.01408627]
 ...
 [ 0.00742417 -0.015124    0.00057336 ...  0.00124304 -0.00261695
  -0.00258313]
 [-0.00529448  0.00314887 -0.00428391 ... -0.00364557 -0.00038221
  -0.00845224]
 [-0.00672167  0.00675424 -0.00357946 ... -0.00773316 -0.00805247
  -0.00849721]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]


In [714]:
def linear_forward(A, W, b):
    
    Z = np.dot(W, A) + b
  
    assert(Z.shape == (W.shape[0], A.shape[1]))
    cache = (A, W, b)
    
    return Z, cache

In [715]:
#test

Z, cache = linear_forward(X_train.T, parameters["W1"], parameters["b1"])
Z

array([[-0.05714644, -0.00266152,  0.00646522, ..., -0.01518216,
        -0.01292219, -0.00513865],
       [ 0.02983454,  0.0421782 ,  0.00559264, ...,  0.00590659,
         0.00772138,  0.00925475],
       [-0.01944083, -0.00708959,  0.01523736, ...,  0.00278694,
         0.01075801,  0.0023635 ],
       ...,
       [-0.004442  ,  0.01014019, -0.01965101, ..., -0.02005649,
        -0.00842171,  0.01052474],
       [ 0.01961826, -0.01523064, -0.00797685, ..., -0.00803453,
        -0.01174948,  0.0278899 ],
       [ 0.01624779,  0.03448916,  0.02464467, ...,  0.02016085,
        -0.00414717, -0.00194617]])

In [716]:
def sigmoid(Z):
    
    A = 1 / (1 + np.exp(- Z))
    
    return A, Z

In [717]:
def relu(Z):
    
    a = Z * (Z >= 0)
    
    return a, Z

In [718]:
def linear_activation_forward(A_prev, W, b, activation):
   
    if activation == "sigmoid":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = sigmoid(Z)
       
    
    elif activation == "relu":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = relu(Z)
       
    
    assert (A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, activation_cache)
    

    return A, cache

In [719]:
#test

A, cache = linear_activation_forward(X_train.T, parameters["W1"], parameters["b1"], activation= "relu")
A.shape

(100, 28800)

In [720]:
def L_model_forward(X, parameters):
   

    caches = []
    A = X
    L = len(parameters) // 2                  # number of layers in the neural network
    
    # Implementing [LINEAR -> RELU]*(L-1). Adding "cache" to the "caches" list.
    for l in range(1, L):
        A_prev = A 
        
        A, cache = linear_activation_forward(A_prev, parameters["W" + str(l)], parameters["b" + str(l)], activation= "relu")
        caches.append(cache)
    
    #print(A.min())
        
    
    # Implementing LINEAR -> RELU. Adding "cache" to the "caches" list.
    
    AL, cache = linear_activation_forward(A, parameters["W" + str(L)], parameters["b" + str(L)], activation= "relu")
    #AL, cache = linear_forward(A, parameters["W" + str(L)], parameters["b" + str(L)])
    caches.append(cache)
   
    
    assert(AL.shape == (1,X.shape[1]))
    #print (AL)
            
    return AL, caches

In [721]:
#test

AL, cache = L_model_forward(X_train.T, parameters)

In [722]:
AL.min()

-0.0

In [723]:
def compute_cost(AL, Y, cache, layers_dims, lambd):
    
    m = Y.shape[1]
    
    cost = - (np.sum(np.square(Y - AL))) / (2 * m)
    
    assert(cost.shape == ())
    
    return cost

In [724]:
def L2_regularization_cost(cache, y, layers_dims, lambd):
    
    total = 0
    for i in range(0,len(layers_dims) - 1):
        total = total + np.sum(np.square(cache[i][1]))
        
    L2_cost = total * lambd / (2 * y.shape[1])
    
    return L2_cost

In [725]:
L2 = L2_regularization_cost(cache, y_train.T, layers_dims= [57, 10, 1], lambd= 0.7)
L2.shape

()

In [726]:
#test

C = compute_cost(AL, y_train.T, cache, [57, 10, 1], lambd = 0.7)
C.shape

()

#test

C = compute_cost(AL, y_train.T)
C


In [727]:
C.shape

()

In [728]:
def linear_backward(lambd, dZ, cache):
    
    A_prev, W, b = cache
    m = A_prev.shape[1]

    dW = (np.dot(dZ, A_prev.T)) / m + W * lambd / m
    db = (np.sum(dZ, axis=1).reshape(b.shape)) / m
    dA_prev = np.dot(W.T, dZ)
    
    assert (dA_prev.shape == A_prev.shape)
    assert (dW.shape == W.shape)
    assert (db.shape == b.shape)
    
    return dA_prev, dW, db

### test

In [729]:
def sigmoid_back(dA, activation_cache):
    m,q=sigmoid(activation_cache) #m stores the sigmoid return values , q stores the buffer returned
    n=1-m
    
    dZ = dA*m*n
    
    return dZ

sigmoid_back(np.array(([3,4,5],[8,9,0])),np.array(([1,2,3],[4,4,4])))

In [730]:
def relu_back(dA, activation_cache):
    
    a =  1 * (activation_cache >= 0 )
    
    dZ = dA * a
    
    return dZ

In [731]:
def linear_activation_backward(lambd, dA, cache, activation):
    
    linear_cache, activation_cache = cache
    
    if activation == "relu":
       
        dZ = relu_back(dA, activation_cache)
        dA_prev, dW, db = linear_backward(lambd, dZ, linear_cache)
       
        
    elif activation == "sigmoid":
        
        dZ = sigmoid_back(dA, activation_cache)
        dA_prev, dW, db = linear_backward(lambd, dZ, linear_cache)
        
    
    return dA_prev, dW, db

In [732]:
#test

In [733]:
def L_model_backward(AL, Y, caches, lambd):
   
    grads = {}
    L = len(caches) # the number of layers
    m = AL.shape[1]
    Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL
    
    # Initializing the backpropagation
    dAL = Y - AL
   
    
    # Lth layer (SIGMOID -> LINEAR) gradients. Inputs: "dAL, current_cache". Outputs: "grads["dAL-1"], grads["dWL"], grads["dbL"]
    current_cache = caches[L-1]
    grads["dA" + str(L-1)], grads["dW" + str(L)], grads["db" + str(L)] = linear_activation_backward(lambd, dAL, caches[L-1], activation= "relu")
    
    
    # Loop from l=L-2 to l=0
    for l in reversed(range(L-1)):
        # lth layer: (RELU -> LINEAR) gradients.
        # Inputs: "grads["dA" + str(l + 1)], current_cache". Outputs: "grads["dA" + str(l)] , grads["dW" + str(l + 1)] , grads["db" + str(l + 1)] 
        
        current_cache = caches[l]
        dA_prev_temp, dW_temp, db_temp = linear_activation_backward(lambd, grads["dA" + str(l+1)], caches[l], activation= "relu")
        grads["dA" + str(l)] = dA_prev_temp
        grads["dW" + str(l + 1)] = dW_temp
        grads["db" + str(l + 1)] =  db_temp
        

    return grads

In [734]:
#test

In [735]:
def update_parameters(parameters, grads, learning_rate):
    
    
    L = len(parameters) // 2 # number of layers in the neural network

    # Update rule for each parameter.
    for l in range(L):
        parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - learning_rate * grads["dW" + str(l+1)]
        parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - learning_rate * grads["db" + str(l+1)]
   
    return parameters

In [736]:
#test

In [737]:
def L_layer_model(X, Y, layers_dims, lambd, a0, decay_rate, num_iterations , print_cost=True):
   
    np.random.seed(1)
    costs = []                         # keep track of cost
    
    # Parameters initialization. 
    parameters = initialize_parameters(layers_dims)
    
    
    # Loop (gradient descent)
    for i in range(0, num_iterations):
        
        learning_rate = a0 / (1 + decay_rate * i)

        # Forward propagation: 
        AL, caches = L_model_forward(X, parameters)
       
        # Compute cost.
        cost = compute_cost(AL, Y, caches, layers_dims, lambd)
        
        # Backward propagation.
        grads = L_model_backward(AL, Y, caches, lambd)
        
        # Update parameters.
        parameters = update_parameters(parameters, grads, learning_rate)
        
                
        # Print the cost every 100 training example
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
        if print_cost and i % 100 == 0:
            costs.append(cost)
            
   
    
    return parameters

# TRAIN STARTS FROM HERE ..... MODEL FUNTIONS DONE

In [738]:
#test


#Y, b = sigmoid(np.array(Y))

layers_dims = [56,500, 10, 1]

new_para = L_layer_model(X_train.T,y_train.T,layers_dims, lambd = 0.9, a0 = 0.1, decay_rate = 1, num_iterations = 500, print_cost=True)

Cost after iteration 0: -0.004979
Cost after iteration 100: -0.004983
Cost after iteration 200: -0.004983
Cost after iteration 300: -0.004983
Cost after iteration 400: -0.004983


In [291]:
df = pd.read_excel("2017_weather_partial.xlsx")

In [297]:
df.head()

Cloud_Cover  Temperature(C)  ApparentTemperature(C)  Humidity  \
0         0.98           -2.79                   -6.25      0.96   
1         0.98           -2.79                   -6.25      0.96   
2         0.98           -2.79                   -6.25      0.96   
3         0.98           -2.79                   -6.25      0.96   
4         0.98           -3.23                   -6.74      0.98   

   WindSpeed(m/s)  HolidayBool  Year2015  Year2016  Year2017  Year2018  ...    \
0            2.43            1         0         0         1         0  ...     
1            2.43            1         0         0         1         0  ...     
2            2.43            1         0         0         1         0  ...     
3            2.43            1         0         0         1         0  ...     
4            2.41            1         0         0         1         0  ...     

   Month 10  Month 11  Month 12  Day 1  Day 2  Day 3  Day 4  Day 5  Day 6  \
0         0         0         0      0      0      0      0      0      0   
1         0         0         0      0      0      0      0      0      0   
2         0         0         0      0      0      0      0      0      0   
3         0         0         0      0      0      0      0      0      0   
4         0         0         0      0      0      0      0      0      0   

   Day 7  
0      1  
1      1  
2      1  
3      1  
4      1  

[5 rows x 57 columns]

df.drop('Day', axis = 1, inplace =True)
df.drop('Year', axis = 1, inplace =True)
df.drop('Month', axis = 1, inplace =True)
df.drop('Time', axis = 1, inplace =True)

In [298]:
ser1=pd.Series(np.random.rand(35040))
ser2=pd.Series(np.random.rand(35040))
ser3=pd.Series(np.random.rand(35040))
ser4=pd.Series(np.random.rand(35040))
ser5=pd.Series(np.random.rand(35040))

m = np.zeros((5,2))
m[0][0] = df['Cloud_Cover'].mean()
m[0][1] = df['Cloud_Cover'].var()
m[1][0] = df['Temperature(C)'].mean()
m[1][1] = df['Temperature(C)'].var()
m[2][0] = df['ApparentTemperature(C)'].mean()
m[2][1] = df['ApparentTemperature(C)'].var()
m[3][0] = df['Humidity'].mean()
m[3][1] = df['Humidity'].var()
m[4][0] = df['WindSpeed(m/s)'].mean()
m[4][1] = df['WindSpeed(m/s)'].var()

In [299]:
for i in range (35040):
    ser1[i]= ((df.iloc[i][0] - m[0][0]) / m[0][1]) 
    ser2[i]= ((df.iloc[i][1] - m[1][0]) / m[1][1]) 
    ser3[i]= ((df.iloc[i][2] - m[2][0]) / m[2][1]) 
    ser4[i]= ((df.iloc[i][3] - m[3][0]) / m[3][1]) 
    ser5[i]= ((df.iloc[i][4] - m[4][0]) / m[4][1]) 

In [ ]:
n = []
n.append(ser1.max())
n.append(ser2.max())
n.append(ser3.max())
n.append(ser4.max())
n.append(ser5.max())

n

df['Cloud_Cover'] = ser1 / n[0]
df['Temperature(C)'] = ser2 / n[1]
df['ApparentTemperature(C)'] = ser3 / n[2]
df['Humidity'] = ser4 / n[3]
df['WindSpeed(m/s)'] = ser5 / n[4]

df['Cloud_Cover'] = ser1 / n[0]

df['ApparentTemperature(C)'] = ser3 / n[2]
df['Humidity'] = ser4 / n[3]
df['WindSpeed(m/s)'] = ser5 / n[4]

In [431]:
df.head()

Cloud_Cover  ApparentTemperature(C)  Humidity  WindSpeed(m/s)  HolidayBool  \
0     0.950685               -0.699850  0.841327        0.022750            1   
1     0.950685               -0.699850  0.841327        0.022750            1   
2     0.950685               -0.699850  0.841327        0.022750            1   
3     0.950685               -0.699850  0.841327        0.022750            1   
4     0.950685               -0.720569  0.947109        0.020298            1   

   Year2015  Year2016  Year2017  Year2018  Tmin00-15       ...        \
0         0         0         1         0          1       ...         
1         0         0         1         0          0       ...         
2         0         0         1         0          0       ...         
3         0         0         1         0          0       ...         
4         0         0         1         0          1       ...         

   Month 11  Month 12  Day 1  Day 2  Day 3  Day 4  Day 5  Day 6  Day 7  \
0         0         0      0      0      0      0      0      0      1   
1         0         0      0      0      0      0      0      0      1   
2         0         0      0      0      0      0      0      0      1   
3         0         0      0      0      0      0      0      0      1   
4         0         0      0      0      0      0      0      0      1   

   Temperature(C)  
0       -0.637265  
1       -0.637265  
2       -0.637265  
3       -0.637265  
4       -0.657586  

[5 rows x 57 columns]

#np.mean(df['Cloud_Cover'])
df.drop('Temperature(C)', axis = 1, inplace =True)
df.head()

df.drop("Time", axis = 1, inplace = True)
df.drop("Day", axis = 1, inplace = True)
df.drop("Year", axis = 1, inplace = True)
df.drop("Month", axis = 1, inplace = True)

In [417]:
K = np.zeros((32000, 56))
for i in range(0,32000):
    for j in range(0, 56):
        K[i][j]=df.iloc[i][j]
    if i % 1000 == 0:
        print(i)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000


In [453]:
dfY = pd.read_excel("final2017LoadData.xlsx")

In [690]:
M = np.zeros((32000, 1))
for i in range(0,32000):
    M[i][0] = (dfY.iloc[i][2]/100000)

In [691]:
X = np.array(K.T)
Y = np.array(M.T)

In [692]:
Y.min()

0.0655

# Train-Test Split

In [590]:
from sklearn.model_selection import train_test_split

In [693]:
#X should be m*n where m is number of examples and n is number of factors
#Y should be m*1 where m is number of examples

In [698]:
X_train, X_test, y_train, y_test = train_test_split(X.T,Y.T, test_size=0.1)

In [699]:
X_dev , X_test , y_dev , y_test = train_test_split(X_test,y_test,test_size=0.3)

In [700]:
X_train.shape

(28800, 56)

In [595]:
#print(y_train.shape ,'Helllllo\n\n\n', X_dev.shape ,'Helllllo\n\n\n', X_test.shape)

# Test Case

K_test = np.zeros((1,60))

for i in range(0, 60):
    if i == 57:
        K_test[0][i] = df.iloc[32002][i] / 10000000
    elif i == 58:
        K_test[0][i] = df.iloc[32002][i] / 10000
    elif i == 59:
        K_test[0][i] = df.iloc[32002][i] / 10000
    else:
        K_test[0][i] = df.iloc[32002][i]

Y_test, b = sigmoid((dfY.iloc[32002][2]) / 10000)
X_test = np.array(K_test.T)

In [745]:
# Test

Y_hat, extra = L_model_forward(X_test.T, new_para)

Y_hat
a = (abs(float(y_test[200][0]) - float(Y_hat.T[1][0])) * 100) / y_test[1][0]
e=[]
for i in range(960):
    e.append((abs(float(y_test[i][0]) - float(Y_hat.T[i][0])) * 100) / y_test[i][0])

#print("The error in your prediction is: " + str(e) + " %")

In [747]:
Y_hat

array([[-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0.

In [744]:
sum(e)/len(e)

100.0

In [44]:
error=[]
for i in range(960):
    m = - np.log((1 / (float(Y_hat.T[i][0]))) - 1) * 10000
    n = - np.log((1 / (float(y_test[i][0]))) - 1) * 10000
    error.append((abs(float(m) - float(n)) * 100) / float(n))
print("The error in your prediction is: " + str(sum(error)/960) + " %")

The error in your prediction is: -6.925861926336892 %


In [95]:
y_train.T.shape

(1, 28800)

In [97]:
y_train

array([[0.73805813],
       [0.72501983],
       [0.74255675],
       ...,
       [0.74276698],
       [0.71408348],
       [0.75046616]])

In [103]:
X_train.T

array([[ 0.75,  0.43,  0.75, ...,  0.81,  0.57,  0.39],
       [14.15, 22.62, 14.08, ...,  2.87, 19.04, 15.81],
       [14.15, 22.62, 14.08, ...,  2.87, 19.04, 15.81],
       ...,
       [ 1.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ]])

In [104]:
y_train.T

array([[0.73805813, 0.72501983, 0.74255675, ..., 0.74276698, 0.71408348,
        0.75046616]])

In [429]:
X_train.T

array([[-0.08493049, -0.20821804, -0.38082062, ...,  0.43287724,
        -0.43013564, -0.89862836],
       [-0.42161574, -0.17424953,  0.43718901, ..., -0.15987269,
        -0.11378223,  0.75263379],
       [ 0.6297638 ,  0.57687292, -1.22141719, ...,  0.78843646,
         0.15374583, -1.27430807],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ]])

(1, 960)